version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /auth-service
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /devdash
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /auth-service
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /devdash
    schedule:
      interval: weekly
